/**
 * manager.js — the test-session manager page.
 *
 * Reads the changesets out of `chrome.storage.local`, renders them, and asks an
 * Adminer tab to run a rollback. It never fetches Adminer itself: from this
 * page's origin such a request is cross-site, and the PHP session cookie — Lax
 * by default — would simply not be attached, so the fetch would come back as the
 * login screen and be parsed as "no rows". Delegating to the tab keeps every
 * request same-origin, which is also the only place the CSRF token is valid.
 *
 * Statement text shown here is generated by the same `undo.js` the rollback
 * runs, so the preview cannot drift from what actually executes.
 */

import * as store from './session.js';
import { sessionUndoScript, blockingReason, columnsToRestore } from './undo.js';
import { joinStatements, engineOf } from './sqlquote.js';
import { connLabel } from './params.js';
import { t, setLang, getLang } from './i18n.js';

const THEME_KEY = 'popupTheme';

const el = (id) => document.getElementById(id);
const ui = {};
let sessions = {};
let currentId = '';
let selected = new Set();
let settings = null;

/* === Boot ════════════════════════════════════════════════════════════════ */

init();

async function init() {
  for (const id of [
    'sessionList', 'detailHead', 'sessName', 'sessMeta', 'sessState', 'changeList', 'changeHead',
    'changeCount', 'chkAll', 'report', 'btnRollback', 'btnExportSql', 'btnExportJson', 'btnRename',
    'btnToggleOpen', 'btnDelete', 'btnSettings', 'btnLang', 'langLabel', 'settingsDlg', 'toast',
  ]) ui[id] = el(id);

  settings = await store.getSettings();
  setLang(settings.lang);
  applyTheme();
  paintStatic();
  wire();

  await reload();
  const wanted = new URLSearchParams(location.search).get('session');
  select(wanted && sessions[wanted] ? wanted : Object.keys(sessions)[0] || '');

  chrome.storage.onChanged.addListener((changes, area) => {
    if (area === 'local' && changes.dbtoolsSessions) reload().then(() => render());
  });
}

function applyTheme() {
  chrome.storage.local.get([THEME_KEY], (res) => {
    const theme = res[THEME_KEY] ||
      (matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
    document.documentElement.setAttribute('data-theme', theme);
  });
}

/** Fill every `data-i18n` node — the page ships with empty ones. */
function paintStatic() {
  for (const node of document.querySelectorAll('[data-i18n]')) {
    node.textContent = t(node.dataset.i18n);
  }
  ui.langLabel.textContent = getLang().toUpperCase();
  document.title = t('mgr.title');
}

function wire() {
  ui.btnLang.addEventListener('click', async () => {
    const next = getLang() === 'vi' ? 'en' : 'vi';
    setLang(next);
    settings = await store.setSettings({ lang: next });
    paintStatic();
    render();
  });

  ui.btnSettings.addEventListener('click', () => openSettings());
  ui.chkAll.addEventListener('change', () => {
    const session = sessions[currentId];
    if (!session) return;
    selected = ui.chkAll.checked
      ? new Set(session.changes.filter((c) => !c.undone).map((c) => c.id))
      : new Set();
    render();
  });

  ui.btnRollback.addEventListener('click', rollbackSelected);
  ui.btnExportSql.addEventListener('click', exportSql);
  ui.btnExportJson.addEventListener('click', exportJson);
  ui.btnRename.addEventListener('click', rename);
  ui.btnToggleOpen.addEventListener('click', toggleOpen);
  ui.btnDelete.addEventListener('click', removeSession);
}

async function reload() {
  sessions = await store.allSessions();
  return sessions;
}

function select(id) {
  currentId = id;
  selected = new Set();
  render();
}

/* === Rendering ═══════════════════════════════════════════════════════════ */

function render() {
  renderRail();
  const session = sessions[currentId];

  ui.detailHead.hidden = !session;
  ui.changeHead.hidden = !session;
  if (!session) {
    ui.changeList.replaceChildren(para(t('mgr.noPreview')));
    return;
  }

  const live = session.changes.filter((c) => !c.undone);
  ui.sessName.textContent = session.name;
  ui.sessState.textContent = session.closedAt ? t('mgr.closed') : t('mgr.open');
  ui.sessState.className = `pill${session.closedAt ? '' : ' open'}`;
  ui.sessMeta.textContent =
    `${connLabel(session.conn)} · ${new Date(session.startedAt).toLocaleString()} · ` +
    `${t('panel.changes', { n: live.length })}`;
  ui.btnToggleOpen.textContent = session.closedAt ? t('mgr.reopen') : t('mgr.close');
  ui.changeCount.textContent = `${live.length} / ${session.changes.length}`;
  ui.btnRollback.disabled = !live.length;

  const list = [...session.changes].sort((a, b) => b.seq - a.seq);
  ui.changeList.replaceChildren(...(list.length ? list.map(renderChange) : [para(t('mgr.empty'))]));
}

function renderRail() {
  const entries = Object.values(sessions)
    .sort((a, b) => String(b.startedAt).localeCompare(String(a.startedAt)));
  if (!entries.length) {
    ui.sessionList.replaceChildren(para(t('mgr.empty')));
    return;
  }
  ui.sessionList.replaceChildren(...entries.map((session) => {
    const live = session.changes.filter((c) => !c.undone).length;
    const button = document.createElement('button');
    button.className = `sess${session.id === currentId ? ' active' : ''}`;
    button.innerHTML = '<span class="t"></span><span class="s"></span>';
    button.querySelector('.t').textContent = session.name;
    button.querySelector('.s').textContent =
      `${connLabel(session.conn)} · ${t('panel.changes', { n: live })}` +
      (session.closedAt ? ` · ${t('mgr.closed')}` : '');
    button.addEventListener('click', () => select(session.id));
    return button;
  }));
}

function renderChange(change) {
  const details = document.createElement('details');
  details.className = `change${change.undone ? ' undone' : ''}`;

  const summary = document.createElement('summary');
  const box = document.createElement('input');
  box.type = 'checkbox';
  box.checked = selected.has(change.id);
  box.disabled = Boolean(change.undone);
  box.addEventListener('click', (e) => e.stopPropagation());
  box.addEventListener('change', () => {
    if (box.checked) selected.add(change.id); else selected.delete(change.id);
  });

  const op = document.createElement('span');
  op.className = `op ${change.op}`;
  op.textContent = t(`op.${change.op}`);

  const table = document.createElement('span');
  table.className = 'tbl';
  table.textContent = change.table || '?';

  const meta = document.createElement('span');
  meta.className = 'meta grow';
  const rows = (change.rows || []).length;
  meta.textContent = `${rows} ${t('mgr.row').toLowerCase()} · ${new Date(change.at).toLocaleTimeString()}` +
    (change.verified === false ? ` · ${t('mgr.unverified')}` : '') +
    (change.undone ? ` · ${t('mgr.undone')}` : '');

  summary.append(box, op, table, meta);

  const reason = blockingReason(change);
  if (reason) {
    const warn = document.createElement('span');
    warn.className = 'warn';
    warn.textContent = `⚠ ${t(`reason.${reason}`)}`;
    summary.append(warn);
  }
  details.append(summary);

  const body = document.createElement('div');
  body.className = 'change-body';
  if (change.statement) {
    const pre = document.createElement('pre');
    pre.className = 'sql';
    pre.textContent = change.statement;
    body.append(pre);
  }
  for (const row of change.rows || []) body.append(renderRow(change, row));
  if ((change.warnings || []).length) {
    const warn = document.createElement('div');
    warn.className = 'warn';
    warn.textContent = `${t('mgr.warnings')}: ${change.warnings.join(', ')}`;
    body.append(warn);
  }
  details.append(body);
  return details;
}

function renderRow(change, row) {
  const table = document.createElement('table');
  table.className = 'diff';
  const head = document.createElement('tr');
  for (const label of [t('mgr.column'), t('mgr.before'), t('mgr.after')]) {
    const th = document.createElement('th');
    th.textContent = label;
    head.append(th);
  }
  table.append(head);

  const caption = document.createElement('caption');
  caption.className = 'meta';
  caption.style.textAlign = 'left';
  caption.textContent = Object.entries(row.where || {})
    .map(([col, value]) => `${col}=${value === null ? 'NULL' : value}`).join(', ') || '—';
  table.prepend(caption);

  const cols = change.op === 'delete'
    ? Object.keys(row.before || {})
    : (change.op === 'insert' ? Object.keys(row.after || {}) : columnsToRestore(change, row));

  for (const col of cols) {
    const tr = document.createElement('tr');
    const name = document.createElement('td');
    name.textContent = col;
    tr.append(name, cell(row.before && row.before[col], 'before'), cell(row.after && row.after[col], 'after'));
    table.append(tr);
  }
  return table;
}

function cell(value, cls) {
  const td = document.createElement('td');
  td.className = `val ${cls}`;
  if (value === null || value === undefined) {
    const i = document.createElement('span');
    i.className = 'null';
    i.textContent = 'NULL';
    td.append(i);
  } else {
    td.textContent = value;
  }
  return td;
}

function para(text) {
  const p = document.createElement('p');
  p.className = 'empty';
  p.textContent = text;
  return p;
}

/* === Actions ═════════════════════════════════════════════════════════════ */

function targetChangeIds(session) {
  if (selected.size) return [...selected];
  return session.changes.filter((c) => !c.undone).map((c) => c.id);
}

/**
 * Hand the rollback to an Adminer tab on the session's origin.
 * Without one there is nothing that can run it, and saying so beats a request
 * that quietly comes back as the login page.
 */
async function rollbackSelected() {
  const session = sessions[currentId];
  if (!session) return;
  if (!settings.autoExecute) {
    showReport(t('mgr.autoExecuteOff'), 'err');
    return;
  }

  const tabs = await chrome.tabs.query({ url: `${session.origin}/*` });
  if (!tabs.length) {
    showReport(t('mgr.needTab', { origin: session.origin }), 'err');
    return;
  }

  ui.btnRollback.disabled = true;
  try {
    const answer = await chrome.tabs.sendMessage(tabs[0].id, {
      type: 'dbtools-run-rollback',
      sessionId: session.id,
      changeIds: targetChangeIds(session),
    });
    await chrome.tabs.update(tabs[0].id, { active: true });
    if (!answer || !answer.ok) {
      showReport(String(answer && answer.error || 'failed'), 'err');
    } else {
      const r = answer.report;
      showReport(t('rollback.done', { ok: r.ok, fail: r.failed }), r.failed ? 'err' : 'ok');
    }
  } catch (err) {
    showReport(String(err && err.message || err), 'err');
  } finally {
    await reload();
    selected = new Set();
    render();
  }
}

function exportSql() {
  const session = sessions[currentId];
  if (!session) return;
  const statements = sessionUndoScript(session, {});
  if (!statements.length) return toast(t('rollback.nothing'));
  const header = `-- ${session.name}\n-- ${connLabel(session.conn)}\n-- ${new Date().toISOString()}\n\n`;
  download(`${slug(session.name)}-undo.sql`, header + joinStatements(statements), 'text/plain');
}

function exportJson() {
  const session = sessions[currentId];
  if (!session) return;
  const engine = engineOf(session.conn && session.conn.driver);
  download(`${slug(session.name)}-changeset.json`, JSON.stringify({ engine, ...session }, null, 2), 'application/json');
}

async function rename() {
  const session = sessions[currentId];
  if (!session) return;
  const name = prompt(t('mgr.rename'), session.name);
  if (name === null) return;
  await store.renameSession(session.id, name.trim() || session.name);
  await reload();
  render();
}

async function toggleOpen() {
  const session = sessions[currentId];
  if (!session) return;
  if (session.closedAt) await store.reopenSession(session.id);
  else await store.closeSession(session.id);
  await reload();
  render();
}

async function removeSession() {
  const session = sessions[currentId];
  if (!session) return;
  const live = session.changes.filter((c) => !c.undone).length;
  if (!confirm(`${t('mgr.delete')}: ${session.name}\n${t('panel.changes', { n: live })}`)) return;
  await store.deleteSession(session.id);
  await reload();
  select(Object.keys(sessions)[0] || '');
}

function openSettings() {
  el('setEnabled').checked = settings.enabled;
  el('setAutoExecute').checked = settings.autoExecute;
  el('setDrift').checked = settings.driftCheck;
  el('setSqlPage').checked = settings.captureSqlPage;
  el('setLimit').value = settings.prefetchLimit;
  el('setEngine').value = settings.engineOverride;

  ui.settingsDlg.addEventListener('close', async () => {
    settings = await store.setSettings({
      enabled: el('setEnabled').checked,
      autoExecute: el('setAutoExecute').checked,
      driftCheck: el('setDrift').checked,
      captureSqlPage: el('setSqlPage').checked,
      prefetchLimit: Math.max(1, Number(el('setLimit').value) || 200),
      engineOverride: el('setEngine').value,
    });
  }, { once: true });
  ui.settingsDlg.showModal();
}

/* === Small helpers ═══════════════════════════════════════════════════════ */

function showReport(text, kind) {
  ui.report.hidden = false;
  ui.report.className = `report ${kind || ''}`;
  ui.report.textContent = text;
}

let toastTimer = 0;
function toast(text) {
  ui.toast.hidden = false;
  ui.toast.textContent = text;
  clearTimeout(toastTimer);
  toastTimer = setTimeout(() => { ui.toast.hidden = true; }, 2600);
}

function slug(name) {
  return String(name).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'session';
}

function download(filename, text, mime) {
  const url = URL.createObjectURL(new Blob([text], { type: mime }));
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
